### ISSUE TITLE
Could you please provide the dataset of the program？

### ISSUE THREAD

**Issue by zhongfansun** [hackerchenzhuo/LaKo#3] opened 2022-09-19 05:49 UTC
Thank you very much for providing this program, it really helped me a lot. But when I ran the program, I found no data, e.g. okvqa_train_t5_v5_frequent_bm25.json

**Comment by hackerchenzhuo** [comment] 2022-09-19 06:14
Please refer to [vqa2_deal](https://github.com/hackerchenzhuo/LaKo/blob/1a48e23e9907b18680dc28e850330e8dff94e055/script/vqa2_deal.py) for details.

Thanks for your comments.

**Comment by zhongfansun** [comment] 2022-09-19 06:31
There are also some files in [vqa2_deal](https://github.com/hackerchenzhuo/LaKo/blob/1a48e23e9907b18680dc28e850330e8dff94e055/script/vqa2_deal.py) I don't know how to generate. Could you please provide them? Thank you very much！

**Comment by hackerchenzhuo** [comment] 2022-10-20 16:02
Those files you mean maybe the Knowledge Base?

**Comment by sujiaqi-1** [comment] 2022-10-27 11:11
![image](https://user-images.githubusercontent.com/66048574/198269487-705dcc0f-132d-4dfd-b096-982c74d51bbf.png)

**Comment by sujiaqi-1** [comment] 2022-10-27 11:13
Could you please provide them? Thank you very much！![image](https://user-images.githubusercontent.com/66048574/198269662-0ba785b1-dd56-40c8-a46b-a876c0d937c1.png)

**Comment by hackerchenzhuo** [comment] 2022-10-27 11:18
Sure, we will release those data as soon as possible @BigHyf  .

Thank you for your attention.

**Comment by zhongfansun** [comment] 2022-10-27 11:19
Thank you very much!

**Comment by BigHyf** [comment] 2022-10-29 08:26
Hi, the script for data processing and  corresponding data source have been uploaded. 

Please contact me if you have any question.

**Comment by xixihawokao** [comment] 2022-10-29 09:53
hi, where can i find the okvqa fact in the program?

**Comment by hackerchenzhuo** [comment] 2022-10-29 10:14
Please refer to [https://github.com/hackerchenzhuo/LaKo/tree/main/data_process](url)

**Comment by xixihawokao** [comment] 2022-10-31 12:22
hi, I can't find the _"3/train.json" and "1/valid.json"_ ? where are they?

**Comment by hackerchenzhuo** [comment] 2022-10-31 13:19
@xixihawokao The '''1''' and '''3''' refer to the occurance frequency.

Thanks for your reminding, I'll upload those files.

**Comment by hackerchenzhuo** [comment] 2022-10-31 13:29
Hi @xixihawokao , I have uploaded the code for [VQA standard data generation](https://github.com/hackerchenzhuo/LaKo/commit/d985c67fe89f8c83b10b2c846439e67c664a0bf6)

Please refer to [https://github.com/hackerchenzhuo/LaKo/blob/main/data_process/deal_data.py](url), where all those input files could be generated.

**Comment by fjwang3** [comment] 2022-11-01 03:21
> Could you please provide them? Thank you very much！![image](https://user-images.githubusercontent.com/66048574/198269662-0ba785b1-dd56-40c8-a46b-a876c0d937c1.png)

Hallo, have you reproduced this work?

**Comment by hanzefang** [comment] 2022-11-01 04:15
I cannot find config and Vector, could you please provide them? Thank you very much！or the config is just python module?
from __future__ import print_function
from config import cfg
import os.path as osp
import pdb
import tqdm
import os
import sys
import json
import numpy as np
from model import Vector

**Comment by hackerchenzhuo** [comment] 2022-11-01 04:51
Due to the fact that the LaKo project has been iterated by several editions, so part of the code, especially those **data processing parts** may be missed or cannot be aligned to the main branch.

@hanzefang  Anyway, thanks for your comment, now they are available at [https://github.com/hackerchenzhuo/LaKo/tree/main/data_process](url)

See the commit above for details.

**Comment by fjwang3** [comment] 2022-11-01 07:36
> Hi @xixihawokao , I have uploaded the code for [VQA standard data generation](https://github.com/hackerchenzhuo/LaKo/commit/d985c67fe89f8c83b10b2c846439e67c664a0bf6)
> 
> Please refer to [https://github.com/hackerchenzhuo/LaKo/blob/main/data_process/deal_data.py](url), where all those input files could be generated.
Hello, I saw the related program you uploaded, but there is still a problem when running: No such file or directory: '3/train.json'

**Comment by hackerchenzhuo** [comment] 2022-11-02 03:47
@wangfengjuan This could be generated using the standard VQA2.0 dataset.

**Comment by fjwang3** [comment] 2022-11-07 07:47
> @wangfengjuan This could be generated using the standard VQA2.0 dataset.



> @wangfengjuan This could be generated using the standard VQA2.0 dataset.
Thank you for your answer, I would like to know what is the content of okvqa_train_t5_v5_frequent_bm25.json? Is it convenient for you to provide it? When I run it, it says there is no such file

**Comment by hackerchenzhuo** [comment] 2022-11-07 07:58
@wangfengjuan Actually, we are sorry that many of those intermediate cache files are deleted earlier.
But in theory, our code should be enough to generate these files.
The **v** in  **okvqa_train_t5_v5_frequent_bm25** refers to *version*. 
Please contact @BigHyf for details.

**Comment by fjwang3** [comment] 2022-11-07 08:04
> 



> @wangfengjuan这可以使用标准的VQA2.0数据集生成。

Do you have the relevant code to generate this file '3/train.json'? thank you for your reply

**Comment by hackerchenzhuo** [comment] 2022-11-07 08:33
@wangfengjuan https://github.com/hackerchenzhuo/LaKo/issues/3#issuecomment-1298025297

**Comment by fjwang3** [comment] 2022-11-07 12:17
> 
Ok, thank you for your reply, the "id2question.json" file is also needed when generating the input file. Where can I find this file? Or is there any relevant code to generate this file?

**Comment by hackerchenzhuo** [comment] 2022-11-07 12:47
> > 
> 
> Ok, thank you for your reply, the "id2question.json" file is also needed when generating the input file. Where can I find this file? Or is there any relevant code to generate this file?

Okay, we‘ll update it recently.

**Comment by hackerchenzhuo** [comment] 2022-11-07 13:02
@wangfengjuan  @xixihawokao They are  available now at:

https://github.com/hackerchenzhuo/LaKo/commit/77157c7041c1ef75a6028d3d4c8603d7e44d944a

**Comment by fjwang3** [comment] 2022-11-08 02:33
> @wangfengjuan @xixihawokao They are available now at:
> 
> [77157c7](https://github.com/hackerchenzhuo/LaKo/commit/77157c7041c1ef75a6028d3d4c8603d7e44d
Thank you for sharing, could you provide these files conveniently? For example: "all_coco_dict_caption.json" and "v5_tripleindex_database_frequent.json" etc. thankyou！

**Comment by hackerchenzhuo** [comment] 2022-11-08 02:39
> > @wangfengjuan @xixihawokao They are available now at:
> > [[77157c7](https://github.com/hackerchenzhuo/LaKo/commit/77157c7041c1ef75a6028d3d4c8603d7e44d944a)]([77157c7](https://github.com/hackerchenzhuo/LaKo/commit/77157c7041c1ef75a6028d3d4c8603d7e44d)
> > Thank you for sharing, could you provide these files conveniently? For example: "all_coco_dict_caption.json" and "v5_tripleindex_database_frequent.json" etc. thankyou！

@wangfengjuan see https://github.com/hackerchenzhuo/LaKo/commit/6f0296ff1217b7db1244f7d994d0ddd9321faf33 and https://github.com/hackerchenzhuo/LaKo/commit/e1140fddd571f0a6a0e3598c27678ce529364a0b

**Comment by fjwang3** [comment] 2022-11-08 02:52
> 

Thank you，and “v5_tripleindex_database_frequent.json" ‘“v5_triplestemindex_database_frequent.json" "relation2template-v2.json"  “image2text.json” still need these documents, sorry for your inconvenience,

**Comment by hackerchenzhuo** [comment] 2022-11-08 02:55
> > 
> 
> Thank you，and “v5_tripleindex_database_frequent.json" ‘“v5_triplestemindex_database_frequent.json" "relation2template-v2.json" “image2text.json” still need these documents, sorry for your inconvenience,

This part of data is missing in my space. Please wait for @BigHyf

**Comment by BigHyf** [comment] 2022-11-08 06:34
> > 
> 
> Thank you，and “v5_tripleindex_database_frequent.json" ‘“v5_triplestemindex_database_frequent.json" "relation2template-v2.json" “image2text.json” still need these documents, sorry for your inconvenience,

These files have already been updated in data_process/data_source.zip

**Comment by fjwang3** [comment] 2022-11-08 07:17
> > > 
> > 
> > 
> > Thank you，and “v5_tripleindex_database_frequent.json" ‘“v5_triplestemindex_database_frequent.json" "relation2template-v2.json" “image2text.json” still need these documents, sorry for your inconvenience,
> 
> These files have already been updated in data_process/data_source.zip

thank you for your replying.

**Comment by fjwang3** [comment] 2022-11-08 08:52
> 
Sorry, could you provide the file "save/vqa2_train_t5_3_v5_frequent_bm25"? thank you!

**Comment by hackerchenzhuo** [comment] 2022-11-08 12:28
I recommend that maybe you could ask all questions at one time or read the code firstly, since most files can actually be generated by our script, like this one.

**Comment by fjwang3** [comment] 2022-11-08 12:45
> I recommend that maybe you could ask all questions at one time or read the code firstly, since most files can actually be generated by our script, like this one.

Sorry, thank you for your suggestion, and some files are not found when running. The file "vqa2_train_t5_3_v5_frequent_bm25_split21" is directly opened in vqa2_deal.py, and I don't see the relevant code to generate this file. I'll take a closer look at the code, sorry to trouble you.

**Comment by BigHyf** [comment] 2022-11-08 13:00
> > I recommend that maybe you could ask all questions at one time or read the code firstly, since most files can actually be generated by our script, like this one.
> 
> Sorry, thank you for your suggestion, and some files are not found when running. The file "vqa2_train_t5_3_v5_frequent_bm25_split21" is directly opened in vqa2_deal.py, and I don't see the relevant code to generate this file. I'll take a closer look at the code, sorry to trouble you.

I do not find..split21 in the updated vqa2_deal.py. Previously, due to the large amount of data generated, we generated 21 copies separately and merged them, but the current code does not have these

**Comment by fjwang3** [comment] 2022-11-08 13:13
yeh，in the updated vqa2_deal.py，"vqa2_train_t5_3_v5_frequent_bm25"  is directly opened，it don't have the relevant code to  generate it. I don't know if you can see this photo.
![image](https://user-images.githubusercontent.com/67569951/200573514-18dae0a6-31a0-4af2-8e94-c926d14ab340.png)

**Comment by BigHyf** [comment] 2022-11-08 14:45
> yeh，in the updated vqa2_deal.py，"vqa2_train_t5_3_v5_frequent_bm25" is directly opened，it don't have the relevant code to generate it. I don't know if you can see this photo. ![image](https://user-images.githubusercontent.com/67569951/200573514-18dae0a6-31a0-4af2-8e94-c926d14ab340.png)

I save the generated okvqa_train_list contents at save/vqa2_train_t5_3_v5_frequent_bm25. It doesn't exist by itself

**Comment by BigHyf** [comment] 2022-11-08 14:48
> yeh，in the updated vqa2_deal.py，"vqa2_train_t5_3_v5_frequent_bm25" is directly opened，it don't have the relevant code to generate it. I don't know if you can see this photo. ![image](https://user-images.githubusercontent.com/67569951/200573514-18dae0a6-31a0-4af2-8e94-c926d14ab340.png)

This is generated and stored, not provided by us, thank you. You can go through the code and run it and ask questions together

**Comment by fjwang3** [comment] 2022-11-09 02:36
> 

thankyou for yur replying，The file "vqa2_train_t5_3_v5_frequent_bm25.json" is missing when running vqa2_deal.py, could you tell us which file it is generated from?

**Comment by hackerchenzhuo** [comment] 2022-11-09 02:53
> > 
> 
> thankyou for yur replying，The file "vqa2_train_t5_3_v5_frequent_bm25.json" is missing when running vqa2_deal.py, could you tell us which file it is generated from?

It should be genertated automatically during running? As a temporary file which is used to accelerate the data generation progress.

**Comment by fjwang3** [comment] 2022-11-09 14:27
> > > 
> > 
> > 
> > thankyou for yur replying，The file "vqa2_train_t5_3_v5_frequent_bm25.json" is missing when running vqa2_deal.py, could you tell us which file it is generated from?
> 
> It should be genertated automatically during running? As a temporary file which is used to accelerate the data generation progress.

I checked the code during the running process of the project, and there is no related file generation. Could you tell us which file was run to generate this file "okvqa_train_t5_v5_frequent_bm25.json"?

**Comment by hackerchenzhuo** [comment] 2022-11-10 04:58
@wangfengjuan  maybe you should first run the following command?

> mkdir save

**Comment by fjwang3** [comment] 2022-11-10 07:23
> @wangfengjuan maybe you should first run the following command?
> 
> > mkdir save

thankyou your replying！

**Comment by YilinGeStudy** [comment] 2023-06-28 08:21
你好，我已经创建了save文件夹，但是里面还是没有东西啊，save/vqa2_train_t5_3_v5_frequent_bm25是哪个代码执行的输出呢？期待您的回复！

**Comment by YilinGeStudy** [comment] 2023-06-28 08:22
@wangfengjuan 请问你的问题解决了吗？我也遇到了同样的问题

**Comment by hackerchenzhuo** [comment] 2023-06-28 08:37
> 你好，我已经创建了save文件夹，但是里面还是没有东西啊，save/vqa2_train_t5_3_v5_frequent_bm25是哪个代码执行的输出呢？期待您的回复！

同学，请问按照前面issue中提到的方法你是不能解决这个问题吗？运行完脚本理论上会在save文件夹下自动生成临时文件的，其他前置数据都已经上传。

因为我们服务器重装过了之前的cache file被清理，我刚才去找没找到备份文件，另一台可能存有这个文件的服务器还在检修，但估计也之前一起被清理了。

**Comment by YilinGeStudy** [comment] 2023-06-28 09:02
你好，我刚刚已经通过python vqa2_deal.py to generate the fact files生成了“home/data_process/save/vqa2_test111_t5_1_v5_frequent_bm25.json”文件，但是只生成了这一个文件，这个结果是正确的吗？
因为我下一步执行bash run_okvqa_train.sh命令时，系统报错如下：
File "train_reader.py", line 236, in <module>
    with open(train_data_path, 'r') as fin:
FileNotFoundError: [Errno 2] No such file or directory: '/data/LaKo/okvqa/okvqa_train_t5_v5_frequent_bm25.json'，请问这个train_reader.py和okvqa_train_t5_v5_frequent_bm25.json在哪里呢？

**Comment by hackerchenzhuo** [comment] 2023-06-28 10:14
@YilinGeStudy  vqa2_deal.py这个文件是生成VQA2.0数据集的tmp文件，应该还生成了一个vqa2_train_t5_3_v5_frequent_bm25.json？
上面生成的数据都是服务于VQA2.0数据集模型训练。

而`bash run_okvqa_train.sh` 是进行OKVQA数据集模型训练的，我刚才检查了上传的处理文件好像确实没有针对OKVQA数据处理的（当然也可能是我遗漏了，这个项目有一段时间了一些细节我自己也忘记了）。也许你可以针对性修改一下 `vqa2_deal.py`脚本中的相关数据输出输出，替换成OKVQA的数据集。你可以看一下代码逻辑，其实很简单。

或者稍等几天，我们另一台可能存有这个文件的老服务器还在检修，过几天检修完成了我去看看之前的数据存档

**Comment by YilinGeStudy** [comment] 2023-06-29 02:13
你好，我现在正在尝试自己处理OKVQA数据，但是依然有下面的疑问：
0. 请问您分享的这个处理VQA.2.0的代码中使用的训练集和测试集的路径为什么都是放在okvqa的文件夹内的呢？（比如home/LaKo-main/data_process/data/okvqa/cache/1/valid）是放错位置了吗？还是您没有分享vqa2.0d的训练集和测试集呢？
1. 你原来处理vqa2.0的代码中使用的训练集和测试集为什么是放在“1”和‘’3‘两个不同的文件夹里面的呢？1和3有什么不同的含义吗？
2. 能否请您解释一下home/LaKo-main/data_process/data/okvqa/cache/1路径下的每个文件内的数据意义呢？我只看您的命名没太搞懂
3. 我点开看到“1”、“10”、“3”、“5”四个文件夹下面的文件都有train.json、test.json、trainval_ans2label.json、trainval_label2ans.json四个文件，能否请您解释一下trainval_ans2label.json和trainval_label2ans.json的意思呢？
4.我看到您原来的代码中有这样的内容：“ # 图像对应caption 文本（注意，这里需要更新）
    with open("all_coco_dict_caption.json", "r", encoding='utf8') as ffp:”，请问如果我处理okvqa数据的话，是否可以直接用您现在分享的这个all_coco_dict_caption.json呢？如果不行的话，需要用哪个代码来生成okvqa图像对应的caption文本呢？

**Comment by BigHyf** [comment] 2023-06-29 02:42
All these contents are on the server of the laboratory. I cannot connect to them from outside at present. I will consult the data source when I can, and then reply to you.

**Comment by hackerchenzhuo** [comment] 2023-06-29 08:10
@YilinGeStudy 
- “1”、“10”、“3”、“5”以及1”和‘’3‘，在论文中是有解释的，代表剔除掉一些长尾答案所要求其低于的最大出现次数。
- 我们之前在数据处理的时候有一些脚本复用的问题，可能这部分处理的不太好，抱歉给你带来麻烦，今天晚上我们会check一下这部分内容。
- 后面这几部分文件的意义解释 @BigHyf 雨峰晚上统一回复。

**Comment by BigHyf** [comment] 2023-06-30 02:19
> 

你好
1、关于okvqa和vqa2.0的部分数据处理的内容已经在data_process文件夹下更新，我们添加了两部分数据的处理脚本和输入数据内容，你可以按需提取。由于这是两年前的处理脚本了，所以可能提供的版本不是最新版，不过能够帮助你来理解我们处理过程。
2、关于caption部分，你可以用我们生成的caption信息，也可以用学术界提供的image2caption相关模型来生成

**Comment by YilinGeStudy** [comment] 2023-06-30 02:28
非常感谢您百忙之中给我答复！我现在就去尝试一下！
还是想问一下，能否请您解释一下trainval_ans2label.json和trainval_label2ans.json的意思呢？他们分别代表什么呢？

**Comment by hackerchenzhuo** [comment] 2023-06-30 02:33
> 非常感谢您百忙之中给我答复！我现在就去尝试一下！ 还是想问一下，能否请您解释一下trainval_ans2label.json和trainval_label2ans.json的意思呢？他们分别代表什么呢？

或许你打开看一下里面的内容应该就看懂了，相当于映射表

**Closed as completed** 2023-07-01 04:51 UTC
Labels: data

**Comment by YilinGeStudy** [comment] 2023-08-24 09:03
你好！我在加载模型"train_reader.py"的权重文件"/data/LaKo/checkpoint/vqa2.0_large_backbone/checkpoint/best_dev"时，遇到了问题，在路径下并没有相关文件，请问您的config.json 文件能麻烦提供一下吗？在您分享的数据资料中我没有找到！谢谢！期待您的回复。

**Comment by YilinGeStudy** [comment] 2023-08-24 09:03
具体报错如下：OSError: Can't load the configuration of '/data/LaKo/checkpoint/vqa2.0_large_backbone/checkpoint/best_dev'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure '/data/LaKo/checkpoint/vqa2.0_large_backbone/checkpoint/best_dev' is the correct path to a directory containing a config.json file

**Comment by hackerchenzhuo** [comment] 2023-08-24 10:42
@YilinGeStudy 同学你好，这个出问题的可能原因是需要调整相关参数，让模型直接从pre-trained 版本的T5开始直接训练会比较合适。理论上训练Reader不需要依赖于任何已有的前置config。

我刚才去看历史文件，存有数据存档的服务器因为暑期高温暂时关闭了，不知道一周内能不能恢复。或许你可以一周后提醒我一下或者先试试其他的方法？

**Comment by YilinGeStudy** [comment] 2023-08-24 10:47
> 同学你好，这个出问题的可能原因是需要调整相关参数，让模型直接从pre-train版本的T5开始直接训练会比较合适。理论上训练Reader不需要依赖于任何已有的前置config。
> 
> 我刚才去看历史文件，存有数据存档的服务器因为暑期高温暂时关闭了，不知道一周内能不能恢复。或许你可以一周后提醒我一下或者先试试其他的方法？
好的，麻烦您看一下啦!期待您下周的回复，服务器应该留有当时的历史数据的，麻烦您啦！

**Comment by YilinGeStudy** [comment] 2023-08-28 03:07
辛苦您抽时间看一下服务器的历史文件~期待您的回复

**Comment by YilinGeStudy** [comment] 2023-08-28 04:51
您的run_okvqa_train.sh文件中的load_path="checkpoint/vqa2.0_large_backbone/checkpoint/best_dev"，所指向的best_dev文件并没有提供，请问这个下载路径您能解释一下吗？并提供一下相关文件，谢谢

**Comment by hackerchenzhuo** [comment] 2023-08-28 06:11
> 辛苦您抽时间看一下服务器的历史文件~期待您的回复

我知道，我这几天每天都上去看了，存了数据的三台服务器一台都连不上。我今天晚上或明天去机房看一下。

我还是建议你可以单独训练一下，训练成本应该三四个小时的样子。checkpoint这个文件夹一般是已经训练好模型存档的地方

**Comment by hackerchenzhuo** [comment] 2023-08-28 06:21
<img width="667" alt="image" src="https://github.com/hackerchenzhuo/LaKo/assets/42081540/881652bf-ffcd-4398-84c8-405989cdceb6">
<img width="439" alt="image" src="https://github.com/hackerchenzhuo/LaKo/assets/42081540/e4f2e33c-393b-44a4-a4c2-95ac6c87ad25">

@YilinGeStudy 同学那可以看一下bash文件里面，这个路径实际上是我提前在VQA2.0上预训练训练好后载入的。你可以直接设置为none。或者自己先在VQA2.0上预训练一下（十几个小时）

**Comment by YilinGeStudy** [comment] 2023-08-28 06:31
请问重新预训练的话是运行哪个文件呢？vqa2_deal.py吗？

**Comment by YilinGeStudy** [comment] 2023-08-28 06:33
> > 辛苦您抽时间看一下服务器的历史文件~期待您的回复
> 
> 我知道，我这几天每天都上去看了，存了数据的三台服务器一台都连不上。我今天晚上或明天去机房看一下。
> 
> 我还是建议你可以单独训练一下，训练成本应该三四个小时的样子。checkpoint这个文件夹一般是已经训练好模型存档的地方

请问单独训练的话是运行哪些文件呢？

**Comment by hackerchenzhuo** [comment] 2023-08-28 07:01
@YilinGeStudy  就参考GitHub的Readme来就好了。

vqa2_deal.py生成的文件我基本都上传了，一些相关的问题你可以参考一下其他的issue

**Comment by YilinGeStudy** [comment] 2023-08-28 07:26
您发的readme里面只写了bash run_okvqa_train.sh这一个操作指令，没有细说单独训练的文件说明呢，我没看明白咱们上传的文件，之前的讨论我也有看的，还是不太懂

**Comment by YilinGeStudy** [comment] 2023-08-28 07:32
![屏幕截图 2023-08-28 153017](https://github.com/hackerchenzhuo/LaKo/assets/128766733/e225f770-495b-4cb0-9838-d7523a5884a0)
您看这个算是单独执行vqa2文件，预训练操作吗？

**Comment by hackerchenzhuo** [comment] 2023-08-28 07:37
vqa2_deal.py 只是处理预训练所需要的数据格式

预训练需要在GPU上跑接近20小时

**Comment by YilinGeStudy** [comment] 2023-08-28 07:41
那我现在想自己预训练，请问指令是bash run_okvqa_train.sh吗？您可能没有理解我的问题，我就是在运行bash run_okvqa_train.sh指令时遇到了错误，因为里面包含着load_path="checkpoint/vqa2.0_large_backbone/checkpoint/best_dev";，即存放与训练数据的文件路径，现在我不清楚这个路径下的文件都应该包含什么，这个checkpoint文件我也没有生成，您没有提供相关的生成方法，麻烦您再看看我之前提的问题，避免理解上的偏差

**Comment by hackerchenzhuo** [comment] 2023-08-28 07:47
load_path可以直接设置为none。这个是可选的内容，相当于载入预训练的模型或者随机初始化

**Comment by hackerchenzhuo** [comment] 2023-08-28 07:52
VQA2.0上预训练完后会得到checkpoint/vqa2.0_large_backbone下所需要的内容

**Comment by YilinGeStudy** [comment] 2023-08-28 07:53
那请问具体如何预训练VQA2.0呢？

**Comment by hackerchenzhuo** [comment] 2023-08-28 07:58
OKVQA和VQA2.0训练流程是一样的。改相关参数就行，时间有点久具体我也印象不深了，你可以针对性地看一下.sh文件，config文件，以及代码

**Comment by YilinGeStudy** [comment] 2023-08-30 05:40
还是想学习一下咱们预训练模型的方法，能具体讲一下有关预训练的运行文件的先后顺序吗？我的目标是最后生成checkpoint文件，现在找不到哪个代码能生成这个文件的，麻烦指点迷津。load_path="checkpoint/okvqa_large_batch_8_maxLen_130_stream_2_content_10_/checkpoint/best_dev"

**Comment by YilinGeStudy** [comment] 2023-08-30 05:42
我按照您之前的提示把load_path设置成了"none"，可以正常训练，运行run_okvqa_train.sh，但是在同样load_path="none"的条件下，run_okvqa_test.sh会报错，说找不到data/LaKo/none文件夹，麻烦您指点迷津

**Comment by YilinGeStudy** [comment] 2023-08-30 05:44
> <img alt="image" width="667" src="https://user-images.githubusercontent.com/42081540/263610271-881652bf-ffcd-4398-84c8-405989cdceb6.png"> <img alt="image" width="439" src="https://user-images.githubusercontent.com/42081540/263610315-e4f2e33c-393b-44a4-a4c2-95ac6c87ad25.png">
> @YilinGeStudy 同学那可以看一下bash文件里面，这个路径实际上是我提前在VQA2.0上预训练训练好后载入的。你可以直接设置为none。或者自己先在VQA2.0上预训练一下（十几个小时）

你好，麻烦您具体说一下预训练VQA2.0的方法，比如执行文件的先后顺序，期待您的回复！感谢！

**Comment by hackerchenzhuo** [comment] 2023-08-30 06:13
因为你需要训练完成才能Test，None就代表没有载入模型。

路径需要设置为你训练好的模型，同学我建议你可以看一下代码，其实很好理解的
